### ISSUE TITLE
Controls should reference their query using `query =` rather than `sql =`

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-mod-github-compliance#27]
It's simpler in code and readability to reference queries using the query = attribute rather than the sql = attribute.

This occurs throughout the mod, but as a specific example:

https://github.com/turbot/steampipe-mod-github-compliance/blob/226cb890cb650fd12455270f95f30ce6e0bdac49/cis_supply_chain_v100/section_1.sp#L69-L81

Could be changed from:
```
sql           = query.default_branch_requires_2_pull_request_reviews.sql
```
to:
```
query         = query.default_branch_requires_2_pull_request_reviews
```

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-mod-github-compliance/pull/39
