### ISSUE TITLE
Update all `resource` columns in queries to use URLs

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-mod-github-compliance#32]
**Is your feature request related to a problem? Please describe.**
Some queries use full names as the `resource` column, while others use `url`.

**Describe the solution you'd like**
The `url` column in GitHub tables seem to be a common column that the API returns, so it may be easiest if we use `url` columns as `resource` in all queries where possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by graza-io** [comment]
https://github.com/turbot/steampipe-mod-github-compliance/commit/5c5ff9b8bcd27c55116113af1dddfe4ba22de52d should resolve.

**Comment by graza-io** [comment]
@cbruno10 this one has been sat in a release branch a while, how do we want to proceed with this?

(Just looking to close out issues where possible)

**Comment by misraved** [comment]
@graza-io we will get it released by EOD 👍. Apologies for missing it.
